### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by GitHubWangPengpeng** [WankkoRee/Portrait2Landscape#1]
大佬什么时候适配一下新版，比如6.83.0版[受虐滑稽]
~~更新后失效了~~😂

**Comment by WankkoRee** [comment]
收到收到，抽空适配。

**Comment by GitHubWangPengpeng** [comment]
> 

突然发现只需要点视频下的三个点，在弹出的窗口中 *我不想看* 下选择竖屏就不会出现竖屏了，然后在设置的播放设置里关闭**竖屏稿件全屏时自动进入看一看**，最后就是以前的样子了。😂

**Comment by WankkoRee** [comment]
欸？那这样子设置后，在首页信息流中还会出现竖屏视频吗？是直接不出现了呢 还是 出现了但是点进去是以前的播放器效果呢？

**Comment by WankkoRee** [comment]
已经适配`6.83.0`了，请更新体验。

**Comment by GitHubWangPengpeng** [comment]
> 

抱歉，才看到消息。像之前那样设置后，我把模块关了，首页中就再也没有竖屏的视频了（直到现在都是这样），以前类型的视频还会推送 但不是竖屏了，点进去跟之前用模块的效果一样，是以前横屏时的样子。

**Comment by GitHubWangPengpeng** [comment]
> 已经适配`6.83.0`了，请更新体验。

好的，谢谢。但是我应该用不到了😂。因为像之前那样设置过后，就再也没有竖屏视频了，现在跟以前一样了，都正常了。感谢适配。

**Comment by WankkoRee** [comment]
哈哈哈好的。
