### ISSUE TITLE
请求适配新版本

### ISSUE THREAD

**Issue by zeronao** [WankkoRee/Portrait2Landscape#3]
老哥如果有空的话，希望能适配一下新版本，哔哩漫游那边好像不打算做了😢

**Comment by WankkoRee** [comment]
新版本是指？我这边`7.12.0`还挺正常的。

**Comment by zeronao** [comment]
> 新版本是指？我这边`7.12.0`还挺正常的。

我6.86都没用啊😂
https://onemanager-15.vercel.app/tmp/

**Comment by WankkoRee** [comment]
这个在 App 的播放设置中关闭以下选项即可。

> 因为本模块只会将原本的**竖屏视频点进去就是*看一看*播放器的全屏状态**改为**竖屏视频点进去还是*传统*播放器的非全屏状态**，至于用户自己操作切换为*看一看*播放器的全屏状态，这个本模块是不作处理的，因为这是用户行为而不是 App 行为。

![Screenshot_2022-12-31-12-36-10-870_tv.danmaku.bili.png](https://user-images.githubusercontent.com/21287731/210124987-81625407-f3a1-4098-a1dc-0e67b4a7216a.png)

![Screenshot_2022-12-31-12-36-08-132_tv.danmaku.bili.png](https://user-images.githubusercontent.com/21287731/210124990-fec3e50b-a510-44b2-bda8-7633bec0a3f4.png)

**Comment by zeronao** [comment]
> 这个在 App 的播放设置中关闭以下选项即可。
> 
> > 因为本模块只会将原本的**竖屏视频点进去就是_看一看_播放器的全屏状态**改为**竖屏视频点进去还是_传统_播放器的非全屏状态**，至于用户自己操作切换为_看一看_播放器的全屏状态，这个本模块是不作处理的，因为这是用户行为而不是 App 行为。
> 
> ![Screenshot_2022-12-31-12-36-10-870_tv.danmaku.bili.png](https://user-images.githubusercontent.com/21287731/210124987-81625407-f3a1-4098-a1dc-0e67b4a7216a.png)
> 
> ![Screenshot_2022-12-31-12-36-08-132_tv.danmaku.bili.png](https://user-images.githubusercontent.com/21287731/210124990-fec3e50b-a510-44b2-bda8-7633bec0a3f4.png)

设置完确实可以了，感谢大佬指点
